version: '3.9'
services:
  cimov:
    image: esouza99/cimov:1.0
    labels:
      - "traefik.http.routers.cimov.rule=Host(`observatorioterraemoradia.com.br`)"
      - "traefik.http.routers.cimov.entrypoints=websecure"
      - "traefik.http.routers.cimov.tls=true"
      - "traefik.http.routers.cimov.tls.certresolver=myresolver"
    expose:
      - 9000
    env_file:
      - ../.env-cimov
    links:
      - db_cimov:dbserver
    restart: always
    depends_on:
      - db_cimov
    networks:
      - cimov

  db_cimov:
    image: mysql:9
    restart: always
    env_file:
      - ../.cimov-dados
    volumes:
      - "mysql_cimov:/var/lib/mysql"
    networks:
      - cimov
    ports:
      - "1433:3306"