version: '3.1'

services:
  db:
    image: mysql:9
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=cimov
      - MYSQL_USER=flasky
      - MYSQL_PASSWORD=flasky
    volumes:
      - cimov_db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  cimov_db: