api:
  dashboard: true
  insecure: true
  debug: false
entryPoints:
  web:
    address: ":80"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: cimov
