"""atualizando tabelas user e formulario

Revision ID: 1e794a642934
Revises: a7330e2a2d5e
Create Date: 2025-04-25 22:30:40.798632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e794a642934'
down_revision = 'a7330e2a2d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_territorios_usuario'), ['usuario'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_nome_completo'), ['nome_completo'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telefone'), ['telefone'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_telefone'))
        batch_op.drop_index(batch_op.f('ix_users_nome_completo'))
        batch_op.drop_index(batch_op.f('ix_users_cpf'))
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.drop_column('telefone')
        batch_op.drop_column('cpf')
        batch_op.drop_column('nome_completo')

    with op.batch_alter_table('territorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territorios_usuario'))
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
