"""empty message

Revision ID: e58b4d193597
Revises: 
Create Date: 2025-04-25 16:06:20.556359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58b4d193597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('qtd_familias', sa.Integer(), nullable=True),
    sa.Column('tempo_ocupacao', sa.String(length=64), nullable=True),
    sa.Column('infraestrutura_bas', sa.Text(), nullable=True),
    sa.Column('risco_ambiental', sa.Text(), nullable=True),
    sa.Column('risco_ambiental_outro', sa.String(length=120), nullable=True),
    sa.Column('comunid_tradicional', sa.String(length=20), nullable=True),
    sa.Column('impacto_grande_proj', sa.String(length=20), nullable=True),
    sa.Column('qual_grande_projeto', sa.String(length=120), nullable=True),
    sa.Column('existe_proc_judicial', sa.String(length=20), nullable=True),
    sa.Column('num_proc_judicial', sa.String(length=120), nullable=True),
    sa.Column('conhece_titular', sa.String(length=20), nullable=True),
    sa.Column('titular', sa.String(length=120), nullable=True),
    sa.Column('relatos_violencia', sa.String(length=20), nullable=True),
    sa.Column('quais_relatos', sa.Text(), nullable=True),
    sa.Column('ameacas_liderancas', sa.String(length=20), nullable=True),
    sa.Column('quais_ameacas', sa.Text(), nullable=True),
    sa.Column('relatos_violencia_adicionais', sa.Text(), nullable=True),
    sa.Column('data', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('territorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territorios_ameacas_liderancas'), ['ameacas_liderancas'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_bairro'), ['bairro'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_comunid_tradicional'), ['comunid_tradicional'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_conhece_titular'), ['conhece_titular'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_existe_proc_judicial'), ['existe_proc_judicial'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_impacto_grande_proj'), ['impacto_grande_proj'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_num_proc_judicial'), ['num_proc_judicial'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_qual_grande_projeto'), ['qual_grande_projeto'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_relatos_violencia'), ['relatos_violencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_risco_ambiental_outro'), ['risco_ambiental_outro'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorios_titular'), ['titular'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territorios_titular'))
        batch_op.drop_index(batch_op.f('ix_territorios_risco_ambiental_outro'))
        batch_op.drop_index(batch_op.f('ix_territorios_relatos_violencia'))
        batch_op.drop_index(batch_op.f('ix_territorios_qual_grande_projeto'))
        batch_op.drop_index(batch_op.f('ix_territorios_num_proc_judicial'))
        batch_op.drop_index(batch_op.f('ix_territorios_nome'))
        batch_op.drop_index(batch_op.f('ix_territorios_impacto_grande_proj'))
        batch_op.drop_index(batch_op.f('ix_territorios_existe_proc_judicial'))
        batch_op.drop_index(batch_op.f('ix_territorios_data'))
        batch_op.drop_index(batch_op.f('ix_territorios_conhece_titular'))
        batch_op.drop_index(batch_op.f('ix_territorios_comunid_tradicional'))
        batch_op.drop_index(batch_op.f('ix_territorios_bairro'))
        batch_op.drop_index(batch_op.f('ix_territorios_ameacas_liderancas'))

    op.drop_table('territorios')
    # ### end Alembic commands ###
